"""add projects, documents, chunks, chat messages

Revision ID: 5465da9329d9
Revises: c95d28b8590e
Create Date: 2026-06-30 15:06:45.312109
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5465da9329d9'
down_revision = 'c95d28b8590e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_documents_project_pmid_unique', 'project_documents', ['project_id', 'pmid'], unique=True, postgresql_where=sa.text('pmid IS NOT NULL'), sqlite_where=sa.text('pmid IS NOT NULL'))
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('queries', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_queries_project_id'), 'queries', ['project_id'], unique=False)
    op.create_foreign_key(
        'fk_queries_project_id_projects',
        'queries', 'projects', ['project_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_queries_project_id_projects', 'queries', type_='foreignkey')
    op.drop_index(op.f('ix_queries_project_id'), table_name='queries')
    op.drop_column('queries', 'project_id')
    op.drop_table('document_chunks')
    op.drop_index('ix_project_documents_project_pmid_unique', table_name='project_documents', postgresql_where=sa.text('pmid IS NOT NULL'), sqlite_where=sa.text('pmid IS NOT NULL'))
    op.drop_table('project_documents')
    op.drop_table('chat_messages')
    op.drop_table('projects')
    # ### end Alembic commands ###
